/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.49
 * Generated at: 2020-05-16 16:50:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      es.uco.pw.display.javabean.CustomerBean customerBean = null;
      synchronized (session) {
        customerBean = (es.uco.pw.display.javabean.CustomerBean) _jspx_page_context.getAttribute("customerBean", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (customerBean == null){
          customerBean = new es.uco.pw.display.javabean.CustomerBean();
          _jspx_page_context.setAttribute("customerBean", customerBean, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
 
if (customerBean.getuserName() != "" ) { 
	 response.sendRedirect("home.jsp");
 } 

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <title>workForAll</title>\r\n");
      out.write("  <meta charset=\"ISO-8859-1\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/wf1.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"loggin\">\r\n");
      out.write("    <!--Cuadro para introducir username, password o si ha olvidado la contraseña-->\r\n");
      out.write("    <div class=\"inicio_sesion\">\r\n");
      out.write("      <form action=\"mvc/control/loginControl.jsp\" method=\"post\" target=\"_self\">\r\n");
      out.write("\r\n");
      out.write("        <!--Introduce el usuario-->\r\n");
      out.write("        Usuario<br>\r\n");
      out.write("        <input type=\"email\" name=\"usuario\" id=\"usuario\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("        <!--Introduce la contraseña-->\r\n");
      out.write("        Contrase&ntilde;a<br>\r\n");
      out.write("        <input type=\"password\" name=\"contr\" id=\"contr\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("        <!--Quiere entrar en la aplicacion-->\r\n");
      out.write("        <input type=\"submit\" value=\"Entrar\">\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!--Unirse si no tienes cuenta-->\r\n");
      out.write("    <div class=\"no_tiene_cuenta\">\r\n");
      out.write("      <p><strong>&Uacute;nete si no tienes cuenta</strong></p>\r\n");
      out.write("      <a href=\"mvc/control/signonControl.jsp\">Crear cuenta</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!--Mensaje de bienvenida-->\r\n");
      out.write("  <h2 class=\"mensaje_inicio\"><strong>Comparte tu vida laboral</strong></h2>\r\n");
      out.write("\r\n");
      out.write("  <!--Definimos la foto de inicio-->\r\n");
      out.write("  <img src=\"img/logo.jpg\" alt=\"LOGO\" class=\"logo_inicio\">\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
